name: MMDLPP
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_2
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2025.7.15=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=py39h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.9.0=pyhff2d567_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - hdf5=1.12.1=h2b7332f_3
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=7_ha36c22a_netlib
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=7_ha36c22a_netlib
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxgboost=2.1.4=h6a678d5_0
  - lightning-utilities=0.11.7=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - mat73=0.65=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.10=py39h5eee18b_0
  - mkl_random=1.2.7=py39h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - pybind11-abi=4=hd3eb1b0_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - python_abi=3.9=2_cp39
  - pytorch=2.0.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39h8cd3c5a_1
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - safetensors=0.4.5=py39he612d8f_0
  - scipy=1.13.1=py39h5f9d8c6_1
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - timm=1.0.9=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.0.2=py39_cu117
  - torchmetrics=1.4.2=pyhd8ed1ab_0
  - torchtriton=2.0.0=py39
  - torchvision=0.15.2=py39_cu117
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - urllib3=2.2.2=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - xgboost=2.1.4=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - abagen==0.1.3
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.6
      - aiosignal==1.3.1
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - autobahn==24.4.2
      - automat==25.4.16
      - cffi==1.17.1
      - cftime==1.6.4.post1
      - click==8.1.7
      - cloudpickle==3.1.0
      - comm==0.2.2
      - constantly==23.10.4
      - contourpy==1.3.0
      - cryptography==44.0.3
      - cycler==0.12.1
      - dask==2024.8.0
      - debugpy==1.8.6
      - decorator==5.1.1
      - enigmatoolbox==2.0.3
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - h5py==3.11.0
      - huggingface-hub==0.30.1
      - hyperlink==21.0.0
      - imageio==2.37.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - incremental==24.7.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.1
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightgbm==4.6.0
      - locket==1.0.0
      - lxml==6.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mne==1.8.0
      - mne-connectivity==0.7.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - nibabel==5.3.2
      - nilearn==0.12.1
      - numpy==1.26.4
      - nvidia-nccl-cu12==2.27.7
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - pandas==2.2.3
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - plotly==5.10.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyvista==0.46.4
      - pyzmq==26.2.0
      - regex==2024.11.6
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scooby==0.11.0
      - seaborn==0.13.2
      - six==1.16.0
      - stack-data==0.6.3
      - tenacity==9.1.2
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - tokenizers==0.13.3
      - toolz==1.0.0
      - torch-cluster==1.6.3+pt20cu117
      - torch-geometric==2.6.0
      - torch-scatter==2.1.2+pt20cu117
      - torch-sparse==0.6.18+pt20cu117
      - tornado==6.4.1
      - traitlets==5.14.3
      - transformers==4.25.1
      - twisted==24.11.0
      - txaio==23.1.1
      - tzdata==2024.2
      - vtk==9.0.2
      - wcwidth==0.2.13
      - wslink==2.3.3
      - xarray==2024.7.0
      - xlsxwriter==3.2.3
      - yarl==1.12.1
      - zipp==3.20.2
      - zope-interface==7.2
prefix: /home/anaconda3/envs/MMDLPP
